=== alumraulgago/Recuperacion_Ej_UD4_LMSGI/Concesionario/concesionario.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="Concesionario">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Coche" maxOccurs="unbounded" minOccurs="0">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="Marca">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="xs:string" name="modelo"/>
                    <xs:element type="xs:string" name="matricula"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element type="xs:short" name="potencia"/>
              <xs:element type="xs:byte" name="plazas"/>
              <xs:element type="xs:byte" name="numeroPuertas"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== alumraulgago/Recuperacion_Ej_UD4_LMSGI/Concesionario/concesionario_xsd.xml
<?xml version="1.0" encoding="UFT-8"?>
<Concesionario xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="concesionario.xsd">
    <Coche>
        <Marca>
            <modelo>Audi A3</modelo>
            <matricula>6548FBJ</matricula>
        </Marca>
        <potencia>200</potencia>
        <plazas>4</plazas>
        <numeroPuertas>4</numeroPuertas>
    </Coche>
    <Coche>
        <Marca>
            <modelo>Lamborgini Murcielago</modelo>
            <matricula>8754BRK</matricula>
        </Marca>
        <potencia>220</potencia>
        <plazas>2</plazas>
        <numeroPuertas>2</numeroPuertas>
    </Coche>
    <Coche>
        <Marca>
            <modelo>Camaro</modelo>
            <matricula>6485BIJ</matricula>
        </Marca>
        <potencia>170</potencia>
        <plazas>2</plazas>
        <numeroPuertas>2</numeroPuertas>
    </Coche>
    <Coche>
        <Marca>
            <modelo>Ferrari f40</modelo>
            <matricula>4899RJR</matricula>
        </Marca>
        <potencia>240</potencia>
        <plazas>2</plazas>
        <numeroPuertas>2</numeroPuertas>
    </Coche>
</Concesionario>
