=== alumraulgago/Recuperacion_Ej_UD4_LMSGI/Gestoria/gestoria.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="Gestoria">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Clientes" maxOccurs="unbounded" minOccurs="0">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="DatosSede">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="xs:string" name="direccionSede"/>
                    <xs:element type="xs:string" name="codigoSede"/>
                      <xs:length value="8"/>
                      <xs:pattern value="[A-Z],\d,\d,\d,\d,\d,\d,\d"/>
                    <xs:element type="xs:string" name="empleado"/>
                    <xs:element type="xs:string" name="date"/>
                    <xs:element type="xs:string" name="descripcion"/>
                      <xs:enumeration value="Solvente"/>
                      <xs:enumeration value="Insolvente"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="Datoscliente">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="xs:string" name="codigoCliente"/>
                      <xs:pattern value="[A-Z],[A-Z], [A-Z], [-], \d , \d, \d"/>
                    <xs:element type="xs:byte" name="numeroViviendas"/>
                    <xs:element type="xs:int" name="coste"/>
                    <xs:element type="xs:string" name="observaciones"/>
                    <xs:element type="xs:string" name="plazoAlta"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== alumraulgago/Recuperacion_Ej_UD4_LMSGI/Gestoria/gestoria_xsd.xml
<?xml version="1.0" encoding="UFT-8"?>
<Gestoria xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="gestoria.xsd">
    <Clientes>
        <DatosSede> 
            <direccionSede>Avenida de la Coronación</direccionSede>
            <codigoSede>G4589842</codigoSede>
            <empleado>Antonio de la Rosa Dominguez</empleado>
            <fecha>04/06/2019</fecha>
            <descripcion>Insolvente</descripcion>
        </DatosSede>
        <Datoscliente>
            <codigoCliente>RTU-498</codigoCliente>
            <numeroViviendas>1</numeroViviendas>
            <coste>1200000</coste>
            <observaciones>Mansión en la zona rica de Madrid</observaciones>
            <plazoAlta>08/02/2021</plazoAlta>
        </Datoscliente>    
    </Clientes>
    <Clientes>
        <DatosSede> 
            <direccionSede>Avenida de la Coronación</direccionSede>
            <codigoSede>G4589842</codigoSede>
            <empleado>Antonio de la Rosa Dominguez</empleado>
            <fecha>18/10/2019</fecha>
            <descripcion>Solvente</descripcion>
        </DatosSede>
        <Datoscliente>
            <codigoCliente>AEV-724</codigoCliente>
            <numeroViviendas>6</numeroViviendas>
            <coste>600000</coste>
            <observaciones>Bloque de apartamentos en el paseo marítimo</observaciones>
            <plazoAlta>20/06/2020</plazoAlta>
        </Datoscliente>    
    </Clientes>
</Gestoria>
